apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongodb-app
          image: lnepel/mongodb-app:0.0.2  # Docker image name
          ports:
            - containerPort: 5000
          env:
            - name: username
              value: "username" # change to your mongodb username
            - name: password
              value: "password" # change to your mongodb password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-app
spec:
  selector:
    app: mongodb-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
